package pl.grzeslowski.jsupla.protocol.api.channeltype.value;

public sealed interface ChannelValue
        permits ActionTrigger,
                ElectricityMeterSimpleValue,
                ElectricityMeterValue,
                CurtainValue,
                DoorLockValue,
                FacadeBlindValue,
                HeatpolThermostatValue,
                HumidityValue,
                HvacValue,
                GateValue,
                GarageDoorValue,
                GatewayLockValue,
                HeatOrColdSourceSwitchValue,
                LightSwitchValue,
                OnOffValue,
                PercentValue,
                PressureValue,
                PowerSwitchValue,
                ProjectorScreenValue,
                PumpSwitchValue,
                RainValue,
                RgbValue,
                RollerGarageDoorValue,
                RollerShutterValue,
                RoofWindowValue,
                StaircaseTimerValue,
                TerraceAwningValue,
                TemperatureAndHumidityValue,
                TemperatureDoubleValue,
                TimerValue,
                UnknownValue,
                VerticalBlindValue,
                WeightValue,
                WindValue {}
